

const productos = [
    // Instrumentos
    { id: 1,
      nombre: "Guitarra Eléctrica", 
        descripcion: "Guitarra eléctrica de alta calidad con 6 cuerdas.",
         precio: 500, categoria: "instrumentos",
          imagen: "/assets/guitarra_electrica.png" },

    { id: 2,
      nombre: "Batería Acústica",
         descripcion: "Set completo de batería acústica con platillos.",
          precio: 800,
           categoria: "instrumentos",
           imagen: "/assets/bateria_acustica.png" },

    { id: 3,
      nombre: "Teclado MIDI",
         descripcion: "Teclado MIDI con 49 teclas y múltiples funciones.",
          precio: 150,
           categoria: "instrumentos",
            imagen: "/assets/teclado_midi.png" },

    { id: 4,
      nombre: "Violín",
         descripcion: "Violín de madera con arco y estuche.",
          precio: 300,
           categoria: "instrumentos",
            imagen: "/assets/violin.png" },

    { id: 5,
      nombre: "Saxofón",
         descripcion: "Saxofón alto de latón con estuche.",
          precio: 600,
           categoria: "instrumentos",
            imagen: "/assets/saxofon.png" },

    { id: 6,
      nombre: "Flauta Traversa",
         descripcion: "Flauta traversa de plata con estuche.",
          precio: 200,
           categoria: "instrumentos",
            imagen: "/assets/flauta_traversa.png" },

    { id: 7,
      nombre: "Bajo Eléctrico",
         descripcion: "Bajo eléctrico de 4 cuerdas con amplificador.",
          precio: 450,
           categoria: "instrumentos",
            imagen: "/assets/bajo_electrico.png" },

    { id: 8,
      nombre: "Trompeta",
         descripcion: "Trompeta de latón con estuche y boquilla.",
          precio: 350,
           categoria: "instrumentos",
            imagen: "/assets/trompeta.png" },

    { id: 9,
      nombre: "Clarinete",
         descripcion: "Clarinete de madera con estuche.",
          precio: 250,
           categoria: "instrumentos",
            imagen: "/assets/clarinete.png" },

    { id: 10,
      nombre: "Guitarra Acústica",
         descripcion: "Guitarra acústica de madera con 6 cuerdas.",
          precio: 200,
           categoria: "instrumentos",
            imagen: "/assets/guitarra_acustica.png" },

    // Amplificadores
    { id: 11,
      nombre: "Amplificador de Guitarra",
         descripcion: "Amplificador de guitarra de 50W.",
          precio: 300,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_guitarra.png" },

    { id: 12,
      nombre: "Amplificador de Bajo",
         descripcion: "Amplificador de bajo de 100W.",
          precio: 400,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_bajo.jpg" },

    { id: 13,
      nombre: "Amplificador de Teclado",
         descripcion: "Amplificador de teclado de 60W.",
          precio: 350,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_teclado.png" },

    { id: 14,
      nombre: "Amplificador de Voz",
         descripcion: "Amplificador de voz portátil con micrófono.",
          precio: 150,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_voz.png" },

    { id: 15,
      nombre: "Amplificador de Batería",
         descripcion: "Amplificador de batería electrónica.",
          precio: 500,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_bateria.png" },

    { id: 16,
      nombre: "Amplificador de Saxofón",
         descripcion: "Amplificador de saxofón con efectos.",
          precio: 450,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_saxofon.webp" },

    { id: 17,
      nombre: "Amplificador de Violín",
         descripcion: "Amplificador de violín con ecualizador.",
          precio: 400,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_violin.webp" },

    { id: 18,
      nombre: "Amplificador de Trompeta",
         descripcion: "Amplificador de trompeta con reverb."
         , precio: 350,
          categoria: "amplificadores",
           imagen: "/assets/amplificador_saxofon.webp" },

    { id: 19,
      nombre: "Amplificador de Clarinete",
         descripcion: "Amplificador de clarinete con distorsión.",
          precio: 300,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_saxofon.webp" },

    { id: 20,
      nombre: "Amplificador de Flauta",
         descripcion: "Amplificador de flauta con chorus.",
          precio: 250,
           categoria: "amplificadores",
            imagen: "/assets/amplificador_saxofon.webp" },

    // Consolas
    { id: 21,
      nombre: "Consola de Mezcla",
         descripcion: "Consola de mezcla de 12 canales.",
          precio: 600,
           categoria: "consolas",
            imagen: "/assets/consola_mezcla.webp" },

    { id: 22,
      nombre: "Consola de DJ",
         descripcion: "Consola de DJ con efectos y loops.",
          precio: 800,
           categoria: "consolas",
            imagen: "/assets/consola_dj.webp" },

    { id: 23,
      nombre: "Consola de Estudio",
         descripcion: "Consola de estudio de grabación.",
          precio: 1000,
           categoria: "consolas",
            imagen: "/assets/consola_estudio.webp" },

    { id: 24,
      nombre: "Consola de Sonido",
         descripcion: "Consola de sonido para eventos en vivo.",
          precio: 1200,
           categoria: "consolas",
            imagen: "/assets/consola_sonido.jfif" },

    { id: 25,
      nombre: "Consola de Karaoke",
         descripcion: "Consola de karaoke con micrófonos.",
          precio: 400,
           categoria: "consolas",
            imagen: "/assets/consola_karaoke.webp" },

    { id: 26,
      nombre: "Consola de Podcast",
         descripcion: "Consola de podcast con múltiples entradas.",
          precio: 500,
           categoria: "consolas",
            imagen: "/assets/consola_podcast.webp" },

    { id: 27,
      nombre: "Consola de Radio",
         descripcion: "Consola de radio con transmisión en vivo.",
          precio: 700,
           categoria: "consolas",
            imagen: "/assets/consola_radio.jpg" },

    { id: 28,
      nombre: "Consola de Video",
         descripcion: "Consola de video con mezcla de audio.",
          precio: 900,
           categoria: "consolas",
            imagen: "/assets/consola_video.webp" },

    { id: 29,
      nombre: "Consola de Streaming",
         descripcion: "Consola de streaming con múltiples salidas.",
          precio: 1100,
           categoria: "consolas",
            imagen: "/assets/consola_streaming.jpg" },

    { id: 30,
      nombre: "Consola de Teatro",
         descripcion: "Consola de teatro con control de luces.",
          precio: 1300,
           categoria: "consolas",
            imagen: "/assets/consola_teatro.jpg" },

    // Accesorios
    { id: 31,
      nombre: "Micrófono Dinámico",
         descripcion: "Micrófono dinámico para voz.",
          precio: 100,
           categoria: "accesorios",
            imagen: "/assets/microfono_dinamico.webp" },

    { id: 32,
      nombre: "Micrófono de Condensador",
         descripcion: "Micrófono de condensador para estudio.",
          precio: 200,
           categoria: "accesorios",
            imagen: "/assets/microfono_condensador.jpg" },

    { id: 33,
      nombre: "Auriculares de Estudio",
         descripcion: "Auriculares de estudio de alta fidelidad.",
          precio: 150,
           categoria: "accesorios",
            imagen: "/assets/auriculares_estudio.jpeg" },

    { id: 34,
      nombre: "Cables XLR",
         descripcion: "Cables XLR de 3 metros.",
          precio: 20,
           categoria: "accesorios",
            imagen: "/assets/cables_xlr.jpg" },

    { id: 35,
      nombre: "Soporte de Micrófono",
         descripcion: "Soporte de micrófono ajustable.",
          precio: 50,
           categoria: "accesorios",
            imagen: "/assets/soporte_microfono.jpg" },

    { id: 36,
      nombre: "Pedal de Efectos",
         descripcion: "Pedal de efectos para guitarra.",
          precio: 120,
           categoria: "accesorios",
            imagen: "/assets/pedal_efectos.jpg" },

    { id: 37,
      nombre: "Afinador de Guitarra",
         descripcion: "Afinador de guitarra digital.", 
          precio: 30,
           categoria: "accesorios",
            imagen: "/assets/afinador_guitarra.jpg" },

    { id: 38,
      nombre: "Cuerdas de Guitarra",
         descripcion: "Juego de cuerdas para guitarra eléctrica.",
          precio: 15,
           categoria: "accesorios",
            imagen: "/assets/cuerdas_guitarra.webp" },

    { id: 39,
      nombre: "Púas de Guitarra",
         descripcion: "Set de 10 púas de guitarra.",
          precio: 10,
           categoria: "accesorios",
            imagen: "/assets/puas_guitarra.jpg" },

    { id: 40,
      nombre: "Capo de Guitarra",
         descripcion: "Capo de guitarra ajustable.",
          precio: 25,
           categoria: "accesorios",
            imagen: "/assets/Capo_guitarra.webp" },

    { id: 41,
      nombre: "Estuche de Guitarra",
         descripcion: "Estuche rígido para guitarra eléctrica.",
          precio: 80,
           categoria: "accesorios",
            imagen: "/assets/estuche_guitarra.jpg" },

    { id: 42,
      nombre: "Soporte de Guitarra",
         descripcion: "Soporte de guitarra plegable.",
          precio: 35,
           categoria: "accesorios",
            imagen: "/assets/soporte_guitarra.jpg" },

    { id: 43,
      nombre: "Correa de Guitarra",
         descripcion: "Correa de guitarra ajustable.",
          precio: 20,
           categoria: "accesorios",
            imagen: "/assets/correa_guitarra.jpg" },

    { id: 44,
      nombre: "Pedal de Volumen",
         descripcion: "Pedal de volumen para guitarra.",
          precio: 100,
           categoria: "accesorios",
            imagen: "/assets/pedal_volumen.jpg" },

    { id: 45,
      nombre: "Caja Directa",
         descripcion: "Caja directa para instrumentos.",
         precio: 60,
          categoria: "accesorios",
           imagen: "/assets/caja_directa.jpg" },

    { id: 46,
      nombre: "Filtro Antipop",
         descripcion: "Filtro antipop para micrófono.",
          precio: 25,
           categoria: "accesorios",
            imagen: "/assets/filtro_antipop.webp" },

    { id: 47,
      nombre: "Atril de Partituras",
         descripcion: "Atril de partituras ajustable.",
          precio: 30,
           categoria: "accesorios",
            imagen: "/assets/atril_partituras.jpg" },

    // Otros
    { id: 48,
      nombre: "Monitor de Estudio",
         descripcion: "Monitor de estudio de alta fidelidad.",
          precio: 300,
           categoria: "varios",
            imagen: "/assets/monitor_estudio.jpg" },

    { id: 49,
      nombre: "Interfaz de Audio",
         descripcion: "Interfaz de audio USB.",
          precio: 150,
           categoria: "varios",
            imagen: "/assets/interface_audio.jpg" },

    { id: 50,
      nombre: "Controlador MIDI",
         descripcion: "Controlador MIDI con pads y faders.",
          precio: 200,
           categoria: "varios",
            imagen: "/assets/controlador_midi.jpg" },
            { id: 51,
              nombre: "Speacker Amplificado",
                 descripcion: "Parlante amplificado profesional 1000 w con usb y bluetooth.",
                  precio: 900,
                   categoria: "varios",
                    imagen: "/assets/parlante_amplificado.webp" }, 
            
];


export default productos;